pygments: true
title: ':wq ~/notes'
tagline: 'Good memory as slow HDD'
description:
url: http://liancheng.github.com/
permalink: /:title
exclude:
paginate: 10
pygments: true
markdown: rdiscount

author:
    name: 连城 (Lian Cheng)
    email: rhythm.mail@gmail.com
    twitter: liancheng
    github: liancheng

attachment_dir: /attachment/
