pygments: true
title: ':wq ~/notes'
tagline: 'Good memory as slow HDD'
description:
url: http://liancheng.github.com/
permalink: /:title
exclude:
paginate: 5
pygments: true
markdown: kramdown
attachment_dir: /attachment/

author:
    name: 连城 (Lian Cheng)
    email: rhythm.mail@gmail.com
    twitter: liancheng
    github: liancheng
    linkedin: liancheng

comments:
    provider: disqus
    disqus:
        short_name: 'lian-blog'
