pygments: true
title: ":wq ~/notes"
description:
url: http://liancheng.github.com/
permalink: /:title

author:
    name: 连城 (Lian Cheng)
    email: rhythm.mail@gmail.com
    twitter: liancheng
    github: liancheng

pygments: true
paginate: 10
exclude:
markdown: rdiscount
image_dir: /static/img/
