pygments: true
title: ':wq ~/notes'
tagline: 'Good memory as slow HDD'
description:
url: http://blog.liancheng.info
permalink: /:title
exclude: [publish]
paginate: 5
pygments: true
markdown: kramdown
attachment_dir: /attachment/

author:
    name: 连城 (Lian Cheng)
    email: rhythm.mail@gmail.com
    twitter: http://twitter.com/liancheng
    github: http://github.com/liancheng
    linkedin: http://cn.linkedin.com/in/liancheng
    facebook: http://www.facebook.com/lianchengzju

comments:
    provider: disqus
    disqus:
        short_name: 'lian-blog'
