pygments: true
title: ':wq ~/notes'
tagline: 'Good memory as slow HDD'
description:
url: http://liancheng.github.com/
permalink: /:title

author:
    name: 连城 (Lian Cheng)
    email: rhythm.mail@gmail.com
    twitter: liancheng
    github: liancheng

pygments: true
paginate: 10
exclude:
markdown: rdiscount
attachment_dir: /attachment/
